services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sakumi_app
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: sakumi
      DB_USERNAME: sakumi
      DB_PASSWORD: sakumi
      DB_SAKUMI_MODE: real
    networks:
      - sakumi_net

  web:
    image: nginx:1.27-alpine
    container_name: sakumi_web
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - sakumi_net

  db:
    image: postgres:16-alpine
    container_name: sakumi_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sakumi
      POSTGRES_USER: sakumi
      POSTGRES_PASSWORD: sakumi
    volumes:
      - sakumi_pgdata:/var/lib/postgresql/data
    networks:
      - sakumi_net

  node:
    image: node:20-alpine
    container_name: sakumi_node
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    entrypoint: ["sh", "-lc"]
    command: ["sleep infinity"]
    networks:
      - sakumi_net

volumes:
  sakumi_pgdata:

networks:
  sakumi_net:
    driver: bridge
